import {
  COLONIZ_HUB_ADDRESS_MAINNET,
  COLONIZ_NFT_CONTRACT_ADDRESS_MAINNET,
  HANDLE_REGISTRY_CONTRACT_ADDRESS_MAINNET,
  HANDLES_CONTRACT_ADDRESS_MAINNET,
  TOKEN_BOUND_ACCOUNT_IMPLEMENTATION_HASH_MAINNET,
  TOKEN_BOUND_ACCOUNT_REGISTRY_ADDRESS_MAINNET,
  TOKEN_BOUND_ACCOUNT_REGISTRY_HASH_MAINNET,
  TOKENBOUND_PROXY_ADDRESS_MAINNET
} from "./mainnet";

import {
  COLONIZ_HUB_ADDRESS_SEPOLIA,
  COLONIZ_NFT_CONTRACT_ADDRESS_SEPOLIA,
  HANDLE_REGISTRY_CONTRACT_ADDRESS_SEPOLIA,
  HANDLES_CONTRACT_ADDRESS_SEPOLIA,
  TOKEN_BOUND_ACCOUNT_IMPLEMENTATION_HASH_SEPOLIA,
  TOKEN_BOUND_ACCOUNT_REGISTRY_ADDRESS_SEPOLIA,
  TOKEN_BOUND_ACCOUNT_REGISTRY_HASH_SEPOLIA,
  TOKENBOUND_PROXY_ADDRESS_SEPOLIA
} from "./sepolia";

const isProduction = process.env.NODE_ENV === "production";

export const HUB_CONTRACT_ADDRESS = isProduction
  ? COLONIZ_HUB_ADDRESS_MAINNET
  : COLONIZ_HUB_ADDRESS_SEPOLIA;
export const COLONIZ_NFT_CONTRACT_ADDRESS = isProduction
  ? COLONIZ_NFT_CONTRACT_ADDRESS_MAINNET
  : COLONIZ_NFT_CONTRACT_ADDRESS_SEPOLIA;
export const TOKEN_BOUND_ACCOUNT_REGISTRY_HASH = isProduction
  ? TOKEN_BOUND_ACCOUNT_REGISTRY_HASH_MAINNET
  : TOKEN_BOUND_ACCOUNT_REGISTRY_HASH_SEPOLIA;
export const TOKEN_BOUND_ACCOUNT_IMPLEMENTATION_HASH = isProduction
  ? TOKEN_BOUND_ACCOUNT_IMPLEMENTATION_HASH_MAINNET
  : TOKEN_BOUND_ACCOUNT_IMPLEMENTATION_HASH_SEPOLIA;
export const HANDLES_CONTRACT_ADDRESS = isProduction
  ? HANDLES_CONTRACT_ADDRESS_MAINNET
  : HANDLES_CONTRACT_ADDRESS_SEPOLIA;
export const TOKEN_BOUND_ACCOUNT_REGISTRY_ADDRESS = isProduction
  ? TOKEN_BOUND_ACCOUNT_REGISTRY_ADDRESS_MAINNET
  : TOKEN_BOUND_ACCOUNT_REGISTRY_ADDRESS_SEPOLIA;
export const HANDLE_REGISTRY_CONTRACT_ADDRESS = isProduction
  ? HANDLE_REGISTRY_CONTRACT_ADDRESS_MAINNET
  : HANDLE_REGISTRY_CONTRACT_ADDRESS_SEPOLIA;
export const TOKENBOUND_PROXY_ADDRESS = isProduction
  ? TOKENBOUND_PROXY_ADDRESS_MAINNET
  : TOKENBOUND_PROXY_ADDRESS_SEPOLIA;

export const ETHER_ADDRESS =
  "0x049d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7";

export const USDC_ADDRESS =
  "0x053c91253bc9682c04929ca02ed00b3e423f6710d2ee7e0d5ebb06f3ecf368a8";

export const USDT_ADDRESS =
  "0x068f5c6a61780768455de69077e07e89787839bf8166decfbf92b645209c0fb8";

export const STRK_ADDRESS =
  "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d";

export const NETWORK = isProduction ? "SN_MAINNET" : "SN_SEPOLIA";
